### ISSUE TITLE
please upgrade mermaid to support gitgraph

### ISSUE THREAD

**Issue by heartacker** [mjbvz/vscode-markdown-mermaid#131]
https://github.com/mermaid-js/mermaid/releases/tag/9.0.0

and the newest version is 9.1.1

**Comment by detj** [comment]
I see mermaid is added as a [devDependency](https://github.com/mjbvz/vscode-markdown-mermaid/blob/9058dc44792c28fe49f582f4bc9b3c153e62cd6d/package.json#L44).

* Why is that?
* Does this extension depend on the mermaid as a [peerDependency](https://docs.npmjs.org/cli/v8/configuring-npm/package-json#peerdependencies)?
* If I need to upgrade the underlying version of mermaid. How do I do that?

**Comment by trongthanh** [comment]
@detj because mermaid is built to the extension bundle at compile time.

I just figured out how to update mermaid bundled with the extension (as a temporary workaround):

- In VSCode, locate extensions folder via command: `Extensions: Open Extensions Folder`
- Open terminal and cd to said folder, then cd to this extension folder (`bierner.markdown-mermaid-1.13.2`)
- Install all dependencies, including devDependencies: `npm install`
- Generate new `page.bundle.js` file (the extension bundle) with command: `npm run build-mermaid`
- That's it. Restart the extension or VSCode to see new mermaid `gitGraph` syntax now render properly.

We don't need to run other build commands.

**Comment by mjbvz** [comment]
At that point, why not just submit a pr :)

**Comment by trongthanh** [comment]
@mjbvz will do. Like I said, it was temporary. But currently I need that gitGraph feature urgently, and I know I cannot rush open source author. :)

**Comment by trongthanh** [comment]
Here you go: #132
