### ISSUE TITLE
Class annotation doesn't work

### ISSUE THREAD

**Issue by dchjmichael** [mjbvz/vscode-markdown-mermaid#39]
[Class Annotations](https://mermaidjs.github.io/#/classDiagram?id=annotations-on-classes) don't work when i try something like this below:

```
classDiagram
class Shape{
    <<interface>>
    noOfVertices
    draw()
}
class Color{
    <<enumeration>>
    RED
    BLUE
    GREEN
    WHITE
    BLACK
}
```

**Comment by dchjmichael** [comment]
It still doesn't work with "Markdown Preview Enhanced" plugin。I've upgraded vscode-markdown-mermaid plugin to the latest version 1.4.1

**Comment by winterhotlatte** [comment]
Strange, it works well for me.

**Comment by dchjmichael** [comment]
> Strange, it works well for me.

yeah. I checked the output html code. It shows "&lt;<interface>&gt;", only escaped the half `<` and `>`. After corrected them manually, the diagram shows normal.

**Comment by mjbvz** [comment]
@dchjmichael That plugin provides its own mermaid version. I don't think this extension will even be used in that case

**Comment by dchjmichael** [comment]
> @dchjmichael That plugin provides its own mermaid version. I don't think this extension will even be used in that case
yeah. Sorry I made a mistake and I opened an issue for that plugin.
The solution here is helpful.
Thanks a lot.

**Comment by NickStavros** [comment]
I am having the same problem.I am not going to edit each of the places that I use it ... ugh! 

But what I found out was that if I use "<< Interface >>" instead of "<<Interface>>"  I get the annotation on the diagram needed to put spaces before and after the chevrons.

**Comment by NickStavros** [comment]
LOL ... even the comment box does not like the ChevronWordChevron but liked the Chevron Word Chevron syntax!

**Comment by agirorn** [comment]
This bug should be reopened since the class annotation doesn't work the same in this plugin as in the mermaid online editor.
 
__I get a "Syntax error in graph mermaid version 8.8.2" error for this example__
```mermaid
classDiagram
class Shape
<<interface>> Shape
```
It works fine in the [Mermaid Live Editor](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiY2xhc3NEaWFncmFtXG5jbGFzcyBTaGFwZVxuPDxpbnRlcmZhY2U-PiBTaGFwZSIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0In0sInVwZGF0ZUVkaXRvciI6ZmFsc2V9)

__This example works fine in the plugin__

```mermaid
classDiagram
class Shape
<< interface >> Shape
```

It works fine in the [Mermaid Live Editor](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiY2xhc3NEaWFncmFtXG5jbGFzcyBTaGFwZVxuPDwgaW50ZXJmYWNlID4-IFNoYXBlIiwibWVybWFpZCI6eyJ0aGVtZSI6ImRlZmF1bHQifSwidXBkYXRlRWRpdG9yIjpmYWxzZX0)

Shouldn't this plugin work the same as the online editor?

**Comment by aaronamm** [comment]
As @NickStavros mentioned, I need to as space after << and before >>.
For example, to use enumeration in a class diagram. I need to do like this.

```
  class TransactionType{
    << enumeration >>
    Revenue
    Expense
  }

```
FYI, I use Mermaid via gatsby-remark-mermaid and update to the latest version with 
`yarn upgrade gatsby-remark-mermaid@^2.1.0`.
