### ISSUE TITLE
How to print result

### ISSUE THREAD

**Issue by JBX028** [mjbvz/vscode-markdown-mermaid#6]
Hi,
I created a nice markdown document that combine real markdown elements as well as several sequence diagrams but now that the document is complete, how can I print or export the result to share the doc with other colleagues?
If I use another markdown editor, the marmaid tag is not going to be recognized I guess, that mean I have to print or export from VS code but I didn't find any options by looking at the preview window or native commands.
Any idea or workaround?

Thanks in advance

Regards,
Johnny -

**Comment by JBX028** [comment]
Hi again,
Unless you come with a better option, I think I found a workaround. I can paste the source code in https://mdp.tylingsoft.com/ and from here, I can export or print the output like for any web pages.
I would prefer to do it by staying in vs code but at least, this solution works fine. Hope it's going to be useful for others as well.

**Comment by unsafecode** [comment]
I believe we will need some additional integration, like https://github.com/yzane/vscode-markdown-pdf, in order to make this work best.

Any tips on where I can start?

**Comment by JBX028** [comment]
Hi,
I have this component installed already but when the pdf is generad, the mermaid syntax is not evaluated that mean, the source code of the diagram is displayed and not the diagram.

**Comment by unsafecode** [comment]
@JBX028 That's what I was meaning :) My intent was to understand how can we integrate the missing feature

**Comment by JBX028** [comment]
Hi,
I haven't checked the vs code sdk to see if the preview panel can be exported or printed. In any cases, I can see that all directives aren't supported such as :fa-arrow-right: supposed to display an arrow so I will probably invest 14$ to buy the full version of markdown plus that support a lot of languages and mermaid is one of them :-)
Anyway, thanks for this vs extension that I will probably continue to use when I will code just to avoid to switch to another editor !

**Comment by mjbvz** [comment]
`:fa-arrow-right:` is a font-awsome syntax feature, not mermaid. Support for these can be added to vscode's markdown preview by an extension the same was `:emoji:` support was added: https://marketplace.visualstudio.com/items?itemName=bierner.markdown-emoji Let me know if you are interested in writing an extension

As for print, VS Code's markdown support targets editing. I've held off an adding `export to html` or `print` to the markdown preview because its beyond this scope and these features introduce new expectations on the preview. Imagine upgrading VSCode versions and now your document prints completely differently for example. Not good.

If we ever implement print for the markdown preview, it would be in core VS Code markdown extension, not in this extension. Closing as upstream

**Comment by beedell-roke** [comment]
> If we ever implement print for the markdown preview, it would be in core VS Code markdown extension, not in this extension. Closing as upstream.

[`microsoft/vscode/issues/5953`](https://github.com/microsoft/vscode/issues/5953#issue-151671632) appears to track that. [^1]

[^1]: [`stackoverflow.com/revisions/72140825/3`](https://stackoverflow.com/revisions/72140825/3#content:~:text=VS%20Code%20does%20not%20support%20the%20printing%20of%20markdown%20or%20anything%20else%2E%20For%20that%20you%20need%20a%20printing%20extension%2E)
